version: '3.7'
services:
  mongodb:
    build: ./mongodb_replica
    ports:
      - '27017:27017'
    volumes:
      - myDb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
volumes:
  myDb: